name: Pack and Prepare opera-gmail

on:
  push:
    branches:
      - main

jobs:
  build-and-pack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Decode .pem Key
        run: |
          echo "$EXTENSION_KEY_B64" | base64 -d -o opera-gmail-key.pem

      - name: Pack Extension with .pem
        run: |
          mkdir -p packed
          /usr/bin/google-chrome \
            --headless \
            --no-sandbox \
            --disable-gpu \
            --pack-extension=./opera-gmail/gmail \
            --pack-extension-key=./opera-gmail-key.pem
          mv ./opera-gmail.crx ./packed/opera-gmail.crx

      - name: Upload Packed Extension
        uses: actions/upload-artifact@v4
        with:
          name: opera-gmail
          path: packed/opera-gmail.crx